[[services]]
name = "devops-mid-lab-backend"
source = "be"

[[services]]
name = "devops-mid-lab-frontend"
source = "fe"

[services.devops-mid-lab-frontend.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
