apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: devops-mid-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-mid-lab-app
  template:
    metadata:
      labels:
        app: devops-mid-lab-app
    spec:
      containers:
      - name: app
        image: ${REPLACE_WITH_ECR_BE_IMAGE}
        imagePullPolicy: Always # For reliable updates
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/devops_mid_lab"
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_URI
        - name: REDIS_URI
          value: redis://redis:6379

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops-mid-lab
spec:
  type: LoadBalancer # Or NodePort for minikube
  selector:
    app: devops-mid-lab-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
