apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-mid-lab
type: Opaque
data:
  # Base64 encoded values
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # password123
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  # mongodb://mongo:27017/devops_mid_lab
  MONGO_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L2Rldm9wc19taWRfbGFi
  # postgresql://postgres:password123@postgres:5432/devops_mid_lab
  POSTGRES_URI: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkMTIzQHBvc3RncmVzOjU0MzIvZGV2b3BzX21pZF9sYWI=
