apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lab-final
type: Opaque
data:
  # Values must be base64 encoded.
  # CI/CD should patch this or create it.
  DATABASE_URL: "cGxhY2Vob2xkZXItZGItdXJs" # placeholder-db-url
